### PR TITLE
Add link to Cake.Markdownlint addin

### PR DESCRIPTION
**Pull request by pascalberger**
Add link to Markdownlint addin for Cake build automation system

### CODE REVIEW

**Comment by DavidAnson** [comment]
Could you please send this PR against “next” branch instead?

**Comment by pascalberger** [comment]
@DavidAnson Sure, rebased and changed target of PR.

**Comment by pascalberger** [comment]
I've some other markdownlint related repos. If you want I can add them here too (or in markdownlint-cli, whatever you prefer):

* [Chocolatey package for installing markdownlint-cli](https://chocolatey.org/packages/markdownlint-cli)
* [Chocolatey package for installation markdownlint extension for Visual Studio Code](https://chocolatey.org/packages/vscode-markdownlint)
* [Cake addin for reading and processing issues reported by markdownlint / markdownlint-cli](https://cakeissues.net/docs/issue-providers/markdownlint/)

**Comment by DavidAnson** [comment]
I’d say:

- CLI
- Extension 
- CLI

**Pull request merged**
