### PR TITLE
Add schedule to run CI once a day at 12:30 UTC.

### PR DESCRIPTION
**Pull request by DavidAnson**

### CODE REVIEW

**Comment by Kreyren** [comment]
Why once a day instead of on push/Merge Request?

**Comment by DavidAnson** [comment]
It’s already did that. This change adds the scheduled daily run as well.

**Comment by DavidAnson** [comment]
For context, please see this thread: https://twitter.com/wesleytodd/status/1211750353571631107?s=21

**Comment by Kreyren** [comment]
thanks, helpful

**Pull request merged**
