### PR TITLE
doc: Add GitHub problem matcher to related projects

### PR DESCRIPTION
**Pull request by nschonni**
[Was looking at implementing this for a project](https://github.com/dotnet/docs/pull/18896), and although I ended up just using the JSON with manual registration, I figure it might be useful for others.

/cc @xt0rted

### CODE REVIEW

**Comment by DavidAnson** [comment]
This is for use with the CLI, right? What do you think about calling that out in the link or nesting it under the link to the CLI?

**Comment by nschonni** [comment]
Done. Also changed Action -> Actions

**Comment by nschonni** [comment]
Not sure what the failure is about, but I'm also seeing `MD013/line-length: Line length [Expected: 70; Actual: 73]` locally in VS Code now, even though that rule is disabled in your config

**Comment by DavidAnson** [comment]
I think the CI issue is that my logic to validate the README in tests is getting confused by the nesting. Maybe un-nest it where you have it now and I’ll look into addressing that and nesting at a future date.

**Comment by nschonni** [comment]
Undid the indent and it looks like the build is happy again. Still seeing vs-code issues around line-length in the file, but not sure it's worth opening an issue for it.

**Comment by DavidAnson** [comment]
VS Code is getting confused by this example:
`<!-- markdownlint-configure-file { "MD013": { "line_length": 70 } } -->`

**Pull request merged**
