### PR TITLE
Add MD030 guide for Prettier users in Rules.md

### PR DESCRIPTION
**Pull request by tats-u**
#410

> You are right. How about adding tips for Prettier users in https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md030 and

### CODE REVIEW

**Comment by tats-u** [comment]
I may have to fix the commit message.

**Review by DavidAnson — CHANGES_REQUESTED** [review]
How about a single new section like:

> Note: The default behavior of Prettier [link to its main page] is xyz. To match that behavior in markdownlint, use the following configuration: [json code block for this rule]

**Comment by DavidAnson** [comment]
I've addressed this slightly differently with https://github.com/DavidAnson/markdownlint/commit/580e57ddeec0d59e65b2872a7e70622fb03858df.

**Comment by tats-u** [comment]
It seems to be better. Thank you.

**Comment by tats-u** [comment]
Sorry for late response.

**Pull request closed without merging**
