### PR TITLE
Add link to Sublime Text markdownlint

### PR DESCRIPTION
**Pull request by jonlabelle**
Added a link to the Sublime Text markdownlint plug-in.

### CODE REVIEW

**Comment by DavidAnson** [comment]
Cool thanks, I love it!

Here’s where I get picky (sorry!). Could you please move that up one line, change it to the form “name for tool“, and squash your commits into one?

Thank you!

**Comment by jonlabelle** [comment]
Okay done. Question though... I made the update for the [PR](https://github.com/jonlabelle/markdownlint) on the `master` branch. Was this incorrect? Or can you just squash them when you perform the merge?

Thanks!

**Comment by DavidAnson** [comment]
It’s unconventional, but not wrong to send a PR from the master branch. It won’t prevent you from squashing yourself, though you will need to do a force push to update this PR.

**Comment by jonlabelle** [comment]
Sounds overly complicated. I'll just make a new PR w/ the requirements.

**Pull request closed without merging**
