### PR TITLE
Fix inline of links with empty link.

### LINKED ISSUE #308: [MD042] no-empty-links: every non-empty link after one empty link is also marked as empty
I am not sure this issue should be posted here or on markdownlint-cli. I can migrate it if its wrong here.

### Minimal file.md

```md
[link1](https://example.com/)
[link2]()
[link3](https://example.com/)
[link3](https://example.com/)
```

### Steps to reproduce

1. Create minimal file.md
2. Execute `markdownlint file.md`

### Actual behavior

The output says link2, link3 and link4 are empty:

```
md.md:2:1 MD042/no-empty-links No empty links [Context: "[link2]()"]
md.md:3 MD042/no-empty-links No empty links [Context: "[link3]()"]
md.md:4 MD042/no-empty-links No empty links [Context: "[link4]()"]
```

### Expected behavior

Only link2 should be flagged as empty.

### PR DESCRIPTION
**Pull request by mondeja**
Closes #308

### CODE REVIEW

**Comment by DavidAnson** [comment]
Looks like a pretty silly mistake on my part, thanks for fixing this! I'll review and merge the PR probably later this evening. In the meanwhile, could you please add two more test cases like the one you did:

Good
Bad
Good
Bad

And

Good
Bad
Good
Bad
Good￼

**Comment by DavidAnson** [comment]
Also, update the PR to be against the "next" branch, rather than "main".

**Comment by mondeja** [comment]
Done, thanks for the quick review!

**Comment by DavidAnson** [comment]
Thanks!

**Pull request merged**
