### PR TITLE
Update yaml config generation

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- [x] more restrictions on property values
- [ ] code refactoring

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I'll recreate PR according to contributing rules.

**Comment by DavidAnson** [comment]
Thanks. Why use exclusiveMinimum instead of minimum? minimum seems easier to understand.

**Comment by EmilySeville7cfg** [comment]
There is no difference in this case - both ways are simple. ;) But I can use `minimum`.

**Comment by DavidAnson** [comment]
Cool, thanks!

**Pull request closed without merging**
