### PR TITLE
feature(MD033): adding tagName filter option to config for "Inline HTML"

### PR DESCRIPTION
**Pull request by rodneyrehm**
Implementation suggestion for #3 - no tests, no docs. I needed a quick fix and thought the solution might help spark an idea or something… :)

### CODE REVIEW

**Comment by DavidAnson** [comment]
Thanks a lot! I'll have a look at this after #2 is taken care of.

**Comment by rodneyrehm** [comment]
Hey @DavidAnson, have you had the chance to take another look at this?

**Comment by DavidAnson** [comment]
No, sorry, I've been busy with a bunch of other things. I haven't forgotten, though - I expect to have time to revisit this in the near-ish future. Thanks for your patience!!

**Comment by DavidAnson** [comment]
The code had diverged enough since the base for your pull request that I took inspiration from it (but didn't try to work through the conflicts).

**Pull request closed without merging**
